# Generated by Django 2.1.15 on 2020-01-22 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='profile_pic',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='position',
        ),
        migrations.AlterField(
            model_name='position',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='pages.Branch'),
        ),
        migrations.AlterField(
            model_name='position',
            name='staff',
            field=models.ManyToManyField(related_name='positions', to='pages.Staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='committees.Committee'),
        ),
    ]
