# Generated by Django 2.1.15 on 2020-01-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200122_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='branch',
        ),
        migrations.AddField(
            model_name='branch',
            name='position',
            field=models.ManyToManyField(blank=True, null=True, related_name='positions', to='pages.Position'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
