# Generated by Django 2.1.15 on 2020-01-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200122_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='position',
            field=models.ManyToManyField(blank=True, null=True, related_name='branches', to='pages.Position'),
        ),
    ]
