# Generated by Django 2.1.15 on 2020-01-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200122_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='branch',
            name='position',
            field=models.ManyToManyField(blank=True, related_name='branches', to='pages.Position'),
        ),
        migrations.AlterField(
            model_name='position',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='positions', to='pages.Staff'),
        ),
    ]
