# Generated by Django 2.1.15 on 2020-01-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='header',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
