# Generated by Django 2.1.15 on 2020-01-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_committee_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='header',
            field=models.ImageField(null=True, upload_to='header/'),
        ),
    ]
