# Generated by Django 2.1.15 on 2020-01-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_auto_20200113_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='full_crisis',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
