# Generated by Django 2.1.15 on 2020-01-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0004_committee_full_crisis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to='header/'),
        ),
    ]
