# Generated by Django 2.1.15 on 2020-01-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0006_auto_20200114_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
