# Generated by Django 2.1.15 on 2020-01-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0007_committee_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='header_x',
            field=models.SmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='committee',
            name='header_y',
            field=models.SmallIntegerField(default=50),
        ),
    ]
