# Generated by Django 2.1.15 on 2020-01-22 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0008_auto_20200114_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='committees.Committee'),
        ),
    ]
