# Generated by Django 2.1.15 on 2020-01-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0009_auto_20200122_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='docket',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
