# Generated by Django 2.1.15 on 2020-01-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0011_remove_committee_docket'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='docket',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
